version: 1
noCache: true

validators:
  # Validators to skip checking PR/issue links of mdox.
  - regex: '(^http[s]?:\/\/)(www\.)?(github\.com\/)bwplotka\/mdox(\/pull\/|\/issues\/)'
    type: 'githubPullsIssues'