name: docs

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Documentation check
    env:
      GOBIN: /tmp/.bin
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Check docs
        run: make check-docs
